name: Docker Image CI

on:
  #push:
  #  branches:
  #  - main
  #  paths:
  #  - Dockerfile
  workflow_dispatch:
    
  pull_request:
    branches:
    - main
    paths:
    - Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      #For architecture emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      #For multi-architecture image building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      # Build the specific stage of the multi-stage Dockerfile
      - uses: actions/checkout@v3

      # Build the DEV stage
      - name: Build DEV stage
        run: docker build --target dev -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:dev .

      # Push the built DEV stage image
      - name: Push DEV stage image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:dev

      # Build the DEPLOY stage
      - name: Build DEPLOY stage
        run: docker build --target deploy -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:deploy .
        
      # Push the built DEPLOY stage image
      - name: Push DEPLOY stage image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPONAME }}:deploy
